### ISSUE TITLE
Error while setting up pod libraries.

### ISSUE THREAD

**Issue by davo** [pwillsey/ForecastIOClient#1]
It's giving me the following error: Error installing AFNetworking

https://gist.github.com/davo/ee67a95a8b68c15487b9

Pod Version: 0.39.0

**Comment by pwillsey** [comment]
Seems like you might have an old version of git that doesn't support the --single-branch option, I would try updating and see if that helps.

**Comment by davo** [comment]
You were just right, I was using the Apple supplied version of git for some weird reason. Thanks!
