### ISSUE TITLE
Future 7 days weather forecast

### ISSUE THREAD

**Issue by qadir-genetech** [pwillsey/ForecastIOClient#2]
How to get weather of 7 up-coming days using your Wrapper library?

As docs says
The Forecast API lets you query for most locations on the globe, and returns:

Current conditions
Minute-by-minute forecasts out to 1 hour (where available)
Hour-by-hour forecasts out to 48 hours
**Day-by-day forecasts out to 7 days**

**Comment by pwillsey** [comment]
Call the forecast method with a valid latitude and longitude, the completion block will return you a Forecast struct with day-by-day forecasts out to 7 days.

``` Swift
ForecastIOClient.sharedInstance.forecast(-75.6046300, longitude: -26.2090000) { (forecast, forecastAPICalls) -> Void in
  if let data = forecast.daily?.data {
    for dataPoint in data {
      print("\(dataPoint.time) - \(dataPoint.temperature)")
    }
  }
}
```

**Comment by qadir-genetech** [comment]
Very nice. Thanks for your support :+1:
