### ISSUE TITLE
How to get more weather details like forecast.io site

### ISSUE THREAD

**Issue by qadir-genetech** [pwillsey/ForecastIOClient#3]
How to get more weather details like forecast.io site like image link given below

https://www.dropbox.com/s/rbusk2067bh33lj/Screenshot%202016-03-20%2015.13.10.png?dl=0

My question is this possible using the forecast.io APIs
I want the values
-> Right Now
-> Clear: Feels Like 9'C
-> Next Hour: _Clear_
-> Next 24 Hours : _Mostly Cloudy, starting this evening_
-> Next 7 days : _Bla bla bla as shown in Image_

**Comment by qadir-genetech** [comment]
Any update please? is this possible using your wrapper library?

**Comment by pwillsey** [comment]
Yes I believe so, "Feels Like" is available through the apparentTemperature field in the currently dataPoint. The rest of the info should be available in the summary property of either the currently dataPoint or the hourly and daily dataBlock.

**Comment by qadir-genetech** [comment]
Thanks for the response. I will look into it today. :)

**Comment by qadir-genetech** [comment]
Thanks for pointing this out. I got the values

I have done like below

```
if let apparentTemperature = forecast.currently?.apparentTemperature {
                    print("apparentTemperature \(apparentTemperature)")
                }

```

```
            if let currentlySummary = forecast.currently?.summary {
                print("currentlySummary \(currentlySummary)")
            }

            if let hourlySummary = forecast.hourly?.summary {
                print("hourlySummary \(hourlySummary)")
            }


            if let hourlyData = forecast.hourly?.data {


                print("-----Loop hourlyData BEGIN-----")
                for data in hourlyData {

                    print("")
                    print("[ time \(data.time)")
                    print("summary \(data.summary!)")
                    print("icon \(data.icon!)")
                    print("temperature \(data.temperature!)")
                    print("apparentTemperature \(data.apparentTemperature!) ]")


                }
                print("-----Loop hourlyData END-----")

            }


            if let dailySummary = forecast.daily?.summary {
                print("dailySummary \(dailySummary)")
            }`
```

and Here is the output

**apparentTemperature** 44.69
**currentlySummary** Drizzle
**hourlySummary** Light rain throughout the day.

**-----Loop hourlyData BEGIN-----**

[ time 1460527200
summary Light Rain
icon rain
temperature 43.58
apparentTemperature 43.58 ]

[ time 1460530800
summary Light Rain
icon rain
temperature 45.57
apparentTemperature 45.57 ]

[ time 1460534400
summary Light Rain
icon rain
temperature 48.48
apparentTemperature 48.48 ]

[ time 1460538000
summary Drizzle
icon rain
temperature 51.64
apparentTemperature 51.64 ]

[ time 1460541600
summary Light Rain
icon rain
temperature 55.29
apparentTemperature 55.29 ]

[ time 1460545200
summary Light Rain
icon rain
temperature 58.11
apparentTemperature 58.11 ]

[ time 1460548800
summary Light Rain
icon rain
temperature 59.05
apparentTemperature 59.05 ]

[ time 1460552400
summary Light Rain
icon rain
temperature 58.07
apparentTemperature 58.07 ]

[ time 1460556000
summary Light Rain
icon rain
temperature 55.32
apparentTemperature 55.32 ]

[ time 1460559600
summary Light Rain
icon rain
temperature 52.04
apparentTemperature 52.04 ]

[ time 1460563200
summary Light Rain
icon rain
temperature 49.21
apparentTemperature 46.45 ]

[ time 1460566800
summary Light Rain
icon rain
temperature 47.61
apparentTemperature 45.13 ]

[ time 1460570400
summary Light Rain
icon rain
temperature 47.28
apparentTemperature 45.13 ]

[ time 1460574000
summary Light Rain
icon rain
temperature 47.58
apparentTemperature 45.79 ]

[ time 1460577600
summary Light Rain
icon rain
temperature 47.62
apparentTemperature 46.06 ]

[ time 1460581200
summary Light Rain
icon rain
temperature 46.88
apparentTemperature 45.26 ]

[ time 1460584800
summary Light Rain
icon rain
temperature 44.43
apparentTemperature 42.3 ]

[ time 1460588400
summary Light Rain
icon rain
temperature 41.01
apparentTemperature 38.05 ]

[ time 1460592000
summary Light Rain
icon rain
temperature 39.19
apparentTemperature 35.7 ]

[ time 1460595600
summary Light Rain
icon rain
temperature 40.09
apparentTemperature 36.66 ]

[ time 1460599200
summary Light Rain
icon rain
temperature 42.45
apparentTemperature 39.41 ]

[ time 1460602800
summary Light Rain
icon rain
temperature 43.73
apparentTemperature 40.9 ]

[ time 1460606400
summary Light Rain
icon rain
temperature 43.32
apparentTemperature 40.36 ]

[ time 1460610000
summary Light Rain
icon rain
temperature 42.54
apparentTemperature 39.24 ]

[ time 1460613600
summary Light Rain
icon rain
temperature 42.0
apparentTemperature 38.47 ]

[ time 1460617200
summary Light Rain
icon rain
temperature 42.52
apparentTemperature 38.82 ]

[ time 1460620800
summary Light Rain
icon rain
temperature 44.31
apparentTemperature 40.59 ]

[ time 1460624400
summary Light Rain
icon rain
temperature 46.59
apparentTemperature 42.96 ]

[ time 1460628000
summary Light Rain
icon rain
temperature 49.62
apparentTemperature 46.38 ]

[ time 1460631600
summary Light Rain
icon rain
temperature 52.9
apparentTemperature 52.9 ]

[ time 1460635200
summary Light Rain
icon rain
temperature 55.48
apparentTemperature 55.48 ]

[ time 1460638800
summary Light Rain
icon rain
temperature 56.99
apparentTemperature 56.99 ]

[ time 1460642400
summary Light Rain
icon rain
temperature 57.35
apparentTemperature 57.35 ]

[ time 1460646000
summary Drizzle
icon rain
temperature 56.55
apparentTemperature 56.55 ]

[ time 1460649600
summary Drizzle
icon rain
temperature 54.05
apparentTemperature 54.05 ]

[ time 1460653200
summary Clear
icon clear-day
temperature 49.83
apparentTemperature 49.83 ]

[ time 1460656800
summary Partly Cloudy
icon partly-cloudy-day
temperature 46.06
apparentTemperature 46.06 ]

[ time 1460660400
summary Partly Cloudy
icon partly-cloudy-night
temperature 43.32
apparentTemperature 43.32 ]

[ time 1460664000
summary Mostly Cloudy
icon partly-cloudy-night
temperature 41.17
apparentTemperature 41.17 ]

[ time 1460667600
summary Mostly Cloudy
icon partly-cloudy-night
temperature 39.63
apparentTemperature 39.63 ]

[ time 1460671200
summary Mostly Cloudy
icon partly-cloudy-night
temperature 38.65
apparentTemperature 36.51 ]

[ time 1460674800
summary Mostly Cloudy
icon partly-cloudy-night
temperature 38.22
apparentTemperature 35.74 ]

[ time 1460678400
summary Partly Cloudy
icon partly-cloudy-night
temperature 38.25
apparentTemperature 35.57 ]

[ time 1460682000
summary Mostly Cloudy
icon partly-cloudy-night
temperature 38.5
apparentTemperature 35.96 ]

[ time 1460685600
summary Mostly Cloudy
icon partly-cloudy-night
temperature 38.54
apparentTemperature 36.18 ]

[ time 1460689200
summary Overcast
icon cloudy
temperature 38.47
apparentTemperature 36.41 ]

[ time 1460692800
summary Overcast
icon cloudy
temperature 39.15
apparentTemperature 39.15 ]

[ time 1460696400
summary Mostly Cloudy
icon partly-cloudy-day
temperature 40.65
apparentTemperature 40.65 ]

[ time 1460700000
summary Mostly Cloudy
icon partly-cloudy-day
temperature 41.78
apparentTemperature 41.78 ]

**-----Loop hourlyData END-----**

dailySummary Light rain today through Monday, with temperatures bottoming out at 56°F on Sunday.
