### ISSUE TITLE
Support swift 3

### ISSUE THREAD

**Issue by qadir-genetech** [pwillsey/ForecastIOClient#4]

**Comment by pwillsey** [comment]
I'll try and add this today

**Comment by qadir-genetech** [comment]
Did you updated the code. please push into repo ASAP.

**Comment by pwillsey** [comment]
Version 0.2.0 is up now

**Comment by qadir-genetech** [comment]
I removed 

pod 'ForecastIOClient'

and executed the command

pod install 

then again added

pod 'ForecastIOClient'

and executed the command again

pod install

did I missed something to update forecastIO

**Comment by qadir-genetech** [comment]
ForecastIOClient uses SwiftyJSON? right
upon updating the ForecastIOClient does this update the SwiftyJSON also?

I am using pods to update your lib i.e pod 'ForecastIOClient'

**Comment by pwillsey** [comment]
You probably need to run `pod repo update` and `pod update` you shouldn't have to remove anything from your Podfile
