### ISSUE TITLE
Issues in Xcode 12.1

### ISSUE THREAD

**Issue by shujaathaider** [pwillsey/ForecastIOClient#6]
@pwillsey Please check this issue.
![image](https://user-images.githubusercontent.com/2362158/98911808-0aabab00-24e7-11eb-84ec-81b7e09c50c9.png)

**Comment by pwillsey** [comment]
Thanks, I'll take a look at this

**Comment by pwillsey** [comment]
This should be fixed in v0.2.3

https://github.com/pwillsey/ForecastIOClient/pull/7

**Comment by shujaathaider** [comment]
Thank you.
